"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AppHeader, HEADER_BTN } from "@/components/AppHeader";
import { createAssignment, deleteAssignment, fetchAssignments, fetchBidPlan, fetchMyProfile, updateAssignment, type AuctionAssignment } from "@/lib/api";
import type { UserProfile } from "@/types/auction";
const allowed = new Set(["student", "consulting_student", "consultant", "admin"]);
type Form = { auctionId:string; auctionNo:string; address:string; marketResearch:string; phoneResearch:string; finalMarketPrice:string; targetBidPrice:string; requiredEquity:string; memo:string };
const empty: Form = { auctionId:"", auctionNo:"", address:"", marketResearch:"", phoneResearch:"", finalMarketPrice:"", targetBidPrice:"", requiredEquity:"", memo:"" };
export default function AssignmentsPage() {
  const [profile,setProfile]=useState<UserProfile|null>(null); const [rows,setRows]=useState<AuctionAssignment[]>([]); const [editing,setEditing]=useState<string|null>(null); const [form,setForm]=useState<Form>(empty); const [message,setMessage]=useState("");
  useEffect(()=>{ fetchMyProfile().then(setProfile).catch(()=>{}); fetchAssignments().then(setRows).catch(e=>setMessage(e.message)); const q=new URLSearchParams(window.location.search), id=q.get("auctionId"); if(id){setForm(x=>({...x,auctionId:id,auctionNo:q.get("auctionNo")||"",address:q.get("address")||""})); fetchBidPlan(id).then(p=>p&&setForm(x=>({...x,targetBidPrice:String(p.bidPrice||""),requiredEquity:String(p.requiredEquity||""),memo:p.memo||x.memo}))).catch(()=>{});}},[]);
  if(profile&&!allowed.has(profile.role)) return <><AppHeader/><main className="mx-auto max-w-4xl p-8"><h1 className="text-2xl font-bold">물건 찾기 과제</h1><p className="mt-4 rounded-xl bg-card p-6">수강생 이상 등급부터 이용할 수 있습니다.</p></main></>;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const body={...form,finalMarketPrice:Number(form.finalMarketPrice)||0,targetBidPrice:Number(form.targetBidPrice)||0,requiredEquity:Number(form.requiredEquity)||0};const row=editing?await updateAssignment(editing,body):await createAssignment(body);setRows(editing?rows.map(x=>x.id===row.id?row:x):[row,...rows]);setEditing(null);setMessage("과제가 저장되었습니다.");}catch(e){setMessage(e instanceof Error?e.message:"저장에 실패했습니다.");}};
  const edit=(r:AuctionAssignment)=>{setEditing(r.id);setForm({auctionId:r.auctionId,auctionNo:r.auctionNo,address:r.address,marketResearch:r.marketResearch,phoneResearch:r.phoneResearch,finalMarketPrice:String(r.finalMarketPrice||""),targetBidPrice:String(r.targetBidPrice||""),requiredEquity:String(r.requiredEquity||""),memo:r.memo});window.scrollTo({top:0,behavior:"smooth"});};
  const remove=async(id:string)=>{if(!window.confirm("이 과제를 삭제할까요?"))return;try{await deleteAssignment(id);setRows(rows.filter(x=>x.id!==id));setMessage("과제를 삭제했습니다.");}catch(e){setMessage(e instanceof Error?e.message:"삭제에 실패했습니다.");}};
  const set=(key:keyof Form,value:string)=>setForm(x=>({...x,[key]:value}));
  return <><AppHeader nav={<><Link className={HEADER_BTN} href="/">추천 물건</Link><Link className={HEADER_BTN} href="/favorites">내 물건</Link><Link className={HEADER_BTN} href="/reports">버그 제보</Link></>}/><main className="mx-auto max-w-5xl space-y-6 p-6"><div><h1 className="text-2xl font-bold">물건 찾기 과제</h1><p className="text-sm text-muted-foreground">입찰계획과 연동해 시세조사와 최종 입찰가를 기록하세요.</p></div><form onSubmit={submit} className="grid gap-3 rounded-xl border bg-card p-5 md:grid-cols-2"><input className="rounded-lg border p-3" placeholder="사건번호" value={form.auctionNo} onChange={e=>set("auctionNo",e.target.value)}/><input className="rounded-lg border p-3" placeholder="물건 주소" value={form.address} onChange={e=>set("address",e.target.value)}/><input className="rounded-lg border p-3" placeholder="최종 시세(원)" value={form.finalMarketPrice} onChange={e=>set("finalMarketPrice",e.target.value)}/><input className="rounded-lg border p-3" placeholder="입찰가(원)" value={form.targetBidPrice} onChange={e=>set("targetBidPrice",e.target.value)}/><textarea className="min-h-24 rounded-lg border p-3" placeholder="주변 물건 시세 조사" value={form.marketResearch} onChange={e=>set("marketResearch",e.target.value)}/><textarea className="min-h-24 rounded-lg border p-3" placeholder="전화 시세 조사 결과" value={form.phoneResearch} onChange={e=>set("phoneResearch",e.target.value)}/><textarea className="min-h-20 rounded-lg border p-3 md:col-span-2" placeholder="메모" value={form.memo} onChange={e=>set("memo",e.target.value)}/><div className="flex gap-2 md:col-span-2"><button className="rounded-lg bg-primary px-4 py-3 font-semibold text-primary-foreground">{editing?"과제 수정":"과제 저장"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty);}} className="rounded-lg border px-4 py-3">취소</button>}</div>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</form><section className="space-y-3"><h2 className="text-lg font-bold">내 과제</h2>{rows.map(r=><article key={r.id} className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><b>{r.auctionNo||"사건번호 미입력"}</b><span className="text-xs text-muted-foreground">{r.status}</span></div><p className="text-sm text-muted-foreground">최종 시세 {Number(r.finalMarketPrice).toLocaleString()}원 · 입찰가 {Number(r.targetBidPrice).toLocaleString()}원</p><p className="mt-2 whitespace-pre-wrap text-sm">{r.marketResearch}</p><div className="mt-3 flex gap-2"><button type="button" onClick={()=>edit(r)} className="rounded border px-3 py-1.5 text-xs">수정</button><button type="button" onClick={()=>remove(r.id)} className="rounded border border-red-200 px-3 py-1.5 text-xs text-red-600">삭제</button></div></article>)}</section></main></>;
}
